package com.example.agrican.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF379237)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF8CF8B9)
val md_theme_light_onPrimaryContainer = Color(0xFF002110)
val md_theme_light_secondary = Color(0xFF4E6355)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E8D6)
val md_theme_light_onSecondaryContainer = Color(0xFF0C1F14)
val md_theme_light_tertiary = Color(0xFF3B6471)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBFE9F8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DC)
val md_theme_light_onSurfaceVariant = Color(0xFF404942)
val md_theme_light_outline = Color(0xFF717972)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1ED)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF6FDB9E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D42)
val md_theme_light_outlineVariant = Color(0xFFC0C9C0)
val md_theme_light_scrim = Color(0xFF000000)

val greenDark = Color(0xFF379237)
val greenLight = Color(0xFF54B435)
val gray = Color(0xFFc6c6c6)
val textGray = Color(0xFF727272)
val iconGray = Color(0xFF5a5a5a)
val white = Color(0xFFFFFFFF)
val black = Color(0xFF000000)
val red = Color(0xFFae2a19)